framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    auto_setup: true
                    exchange:
                        name: books_exchange
                        type: direct
                    queues:
                        books_queue: ~
                retry_strategy:
                    max_retries: 5
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000

        routing:
            App\Messages\LoadBooksMessage: async
