nelmio_cors:
    defaults:
        allow_origin: ['http://localhost', 'http://localhost:3005']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/': ~
