version: "3.9"

services:
  server:
    container_name: server
    image: nginx:alpine
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ".:/var/www/html/"
      - "./config/infrastructure/nginx/conf.d/:/etc/nginx/conf.d/"
      - "./config/infrastructure/nginx/ssl/:/etc/nginx/ssl/"
      - "./config/infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - webapp
    ports:
      - "80:80"
      - "443:443"
    networks:
      - architecht_network

  webapp:
    image: taygeta/php:8.4
    container_name: webapp
    env_file:
      - .env.local
    environment:
      TZ: "Europe/Moscow"
      DB_HOST: "citus-coordinator"  # Используем Citus
      DB_PORT: "5432"
    volumes:
      - ".:/var/www/html/"
    depends_on:
      - citus-coordinator
    networks:
      - architecht_network

  citus-coordinator:
    image: citusdata/citus:12.1.3
    container_name: citus-coordinator
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "app_db"
    ports:
      - "5433:5432"
    volumes:
      - citus_coordinator_data:/var/lib/postgresql/data
      - ./config/infrastructure/postgrespro/.pgpass:/root/.pgpass
    networks:
      - architecht_network

  citus-worker-1:
    image: citusdata/citus:12.1.3
    container_name: citus-worker-1
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      COORDINATOR_HOST: "citus-coordinator"
      CITUS_ROLE_NODE: "worker"
#    volumes:
#      - ./config/infrastructure/postgrespro/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - architecht_network

  citus-worker-2:
    image: citusdata/citus:12.1.3
    container_name: citus-worker-2
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      COORDINATOR_HOST: "citus-coordinator"
      CITUS_ROLE_NODE: "worker"
#    volumes:
#      - ./config/infrastructure/postgrespro/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - architecht_network

networks:
  architecht_network:
    external: true

volumes:
  citus_coordinator_data:
